docker.enabled = true
process.container = 'ubuntu:22.04'
params {
  trim_primers = true
  //uni12, uni13, A_HA_F, A_NA_F, A_HA_R, A_NA_R
  primers_5p_r1 = ["AGCAAAAGCAGG","GAGCAAAAGCAGGGGA","GAGCAAAAGCAGGAGT"]
  primers_5p_r2 = ["AGTAGAAACAAGG","AGTAGAAACAAGGGTG","AGTAGAAACAAGGAGT"]
}
