docker.enabled = true
process.container = 'ubuntu:22.04'

params {
  trim_primers = true

  // 5' trimming candidates for Illumina
  // Includes: overhang handle + Uni-12/Uni-13 + nested HA/NA cores
  primers_5p_r1 = [
    "GTACCGCAGTTGTATGTCCA",  // overhang/handle
    "AGCAAAAGCAGG",          // Uni-12 (A variant)
    "GAGCAAAAGCAGGGGA",      // A-HA-F
    "GAGCAAAAGCAGGAGT"       // A-NA-F
  ]

  primers_5p_r2 = [
    "GTACCGCAGTTGTATGTCCA",  // overhang/handle
    "AGTAGAAACAAGG",         // Uni-13
    "AGTAGAAACAAGGGTG",      // A-HA-R
    "AGTAGAAACAAGGAGT"       // A-NA-R
  ]
}